Promote from BLAIS5-3123 to main
ONSdigital/blaise-management-information-reports pull request #141
Opened 2022-06-20 15:36 UTC by social-surveys-blaise-concourse

Auto generated by concourse:

Promote from BLAIS5-3123 to main

2022-06-21 10:24 UTC, tomphp requested changes

2022-06-21 10:24 UTC, tomphp commented on src/components/QuestionnaireSelector.test.tsx
> +            await flushPromises();
e.g replace with

```typescript
await screen.findByText('LMS2101_AA1');
```

2022-06-21 10:24 UTC, tomphp commented on src/components/QuestionnaireSelector.test.tsx
> +        expect(wrapper.getByText(questionnaire)).toHaveClass("checkbox__label");
Consider `getByRole('checkbox', { ... })`

2022-06-21 10:24 UTC, tomphp commented on src/components/QuestionnaireSelector.test.tsx
> +    await act(async () => {
no need for `act`

2022-06-21 10:24 UTC, tomphp commented on src/components/QuestionnaireSelector.test.tsx
> +    expect(checkBox).toBeChecked;
Should this have `()`?

2022-06-21 10:24 UTC, tomphp commented on src/components/QuestionnaireSelector.test.tsx
> +    await act(async () => {
`act` again

2022-06-21 10:24 UTC, tomphp commented on src/components/QuestionnaireSelector.tsx
> +            return () => {
indented too far

2022-06-22 09:00 UTC, JAWilliamsONS approved these changes
looks good to me :) visual inspection of the code looks good
Deployed to my sandbox, tests passed and functions as expected

2022-06-22 09:00 UTC, JAWilliamsONS approved these changes

2022-06-23 10:29 UTC, elthorne approved these changes

2022-06-23 10:30 UTC, merged